# Natural textures compatibility for Right Proper MCPatcher

# Coral
bettergrassandleaves:better_coral_0 = F
bettergrassandleaves:better_coral_1 = F
bettergrassandleaves:better_coral_2 = F
bettergrassandleaves:better_coral_3 = F
# better_coral_4 and better_coral_5 are excluded,
# as they might look too symmetric when mirrored

bettergrassandleaves:better_crust_0 = 4F
bettergrassandleaves:better_crust_1 = 4F
bettergrassandleaves:better_crust_2 = 4F
bettergrassandleaves:better_crust_3 = 4F

### Generated Textures ###

# Extra Leaves
betterfoliage_gen_leaves:leaves_oak = 2
betterfoliage_gen_leaves:leaves_spruce = 2
betterfoliage_gen_leaves:leaves_birch = 2
betterfoliage_gen_leaves:leaves_jungle = 2
betterfoliage_gen_leaves:leaves_acacia = 2
betterfoliage_gen_leaves:leaves_big_oak = 2

betterfoliage_gen_leaves:leaves_oak_opaque = 2
betterfoliage_gen_leaves:leaves_spruce_opaque = 2
betterfoliage_gen_leaves:leaves_birch_opaque = 2
betterfoliage_gen_leaves:leaves_jungle_opaque = 2
betterfoliage_gen_leaves:leaves_acacia_opaque = 2
betterfoliage_gen_leaves:leaves_big_oak_opaque = 2

# Et Futurum Requiem
betterfoliage_gen_leaves:cherry_leaves = 2
betterfoliage_gen_leaves:cherry_leaves_opaque = 2
