# Natural textures compatibility for Right Proper MCPatcher

bettergrassandleaves:better_crust_0 = 4F
bettergrassandleaves:better_crust_1 = 4F
bettergrassandleaves:better_crust_2 = 4F
bettergrassandleaves:better_crust_3 = 4F
