# Natural textures compatibility for Right Proper MCPatcher

# Coral
bettergrassandleaves:better_coral_0 = F
bettergrassandleaves:better_coral_1 = F
bettergrassandleaves:better_coral_2 = F
bettergrassandleaves:better_coral_3 = F
# better_coral_4 and better_coral_5 are excluded,
# as they might look too symmetric when mirrored

bettergrassandleaves:better_crust_0 = 4F
bettergrassandleaves:better_crust_1 = 4F
bettergrassandleaves:better_crust_2 = 4F
bettergrassandleaves:better_crust_3 = 4F
